#!/usr/bin/env python3
"""
TomTom Unified Ingestion Job - Priority + Spatial Interpolation.

This script implements:
1. Tiered Ingestion: Ingests top 600 points (stations + high-pop wards) hourly.
2. Spatial Interpolation: Fills the remaining 2700 wards using IDW (k=10) + OSM Proxy.
3. Database: Writes to raw_tomtom_traffic with metadata.

Author: Air Quality Data Platform
"""

import os
import sys
import logging
import argparse
import pandas as pd
import numpy as np
from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor, as_completed
from scipy.spatial import cKDTree
from dotenv import load_dotenv

# Add project root to path
_script_dir = os.path.dirname(os.path.abspath(__file__))
# jobs/traffic -> jobs -> python_jobs -> project_root
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(_script_dir)))
sys.path.insert(0, os.path.join(PROJECT_ROOT, "python_jobs"))

from common.api_client import APIClient
from common.token_manager import TokenManager
from common import get_data_writer
from common.ingestion_control import update_control

logger = logging.getLogger(__name__)

def load_enriched_wards():
    """Load wards with OSM metadata generated by preprocessing."""
    path = os.path.join(PROJECT_ROOT, "dbt/dbt_tranform/seeds/vietnam_wards_with_osm.csv")
    if not os.path.exists(path):
        # Fallback to base wards
        logger.warning(f"{path} not found. Running with base coordinates only.")
        path = os.path.join(PROJECT_ROOT, "dbt/dbt_tranform/seeds/vietnam_wards_2026.csv")
    return pd.read_csv(path)

def select_tier_1(df, limit=600):
    """Select top points based on population, ensuring they have a road nearby."""
    # With the new high-res OSM index, most wards will be very close to a road.
    # We prioritize by population to get the most important urban centers as anchors.
    # We still filter for distance <= 1km to avoid truly off-grid points.
    near_roads = df[df['distance_to_road_km'] <= 1.0].copy()
    
    if len(near_roads) < limit:
        return df.sort_values(by=['population'], ascending=False).head(limit)
    
    return near_roads.sort_values(by=['population'], ascending=False).head(limit)

def get_osm_proxy(highway_type, dist_km):
    """
    Calculate a baseline congestion ratio proxy based on OSM context.
    Higher road classes have higher base congestion probability.
    Distance from road inversely affects congestion relevance.
    """
    weights = {
        'motorway': 0.9,
        'trunk': 0.8,
        'primary': 0.7,
        'secondary': 0.5,
        'tertiary': 0.3,
        'residential': 0.1
    }
    base = weights.get(highway_type, 0.2)
    
    # Distance penalty: congestion probability drops as we move away from the nearest road segment
    # e.g., if 1km away, factor is 0.5
    dist_factor = np.exp(-1.0 * dist_km) 
    
    return base * dist_factor

def fetch_traffic_for_point(point_data, client, batch_id):
    """Fetch traffic data for a single point from TomTom."""
    # Priority: Use snapped coordinates (nearest road) to avoid 400 "Point too far" errors
    lat = point_data.get('snapped_lat', point_data['lat'])
    lon = point_data.get('snapped_lon', point_data['lon'])
    code = point_data.get('code', 'unknown')
    
    try:
        # TomTom Point Flow Segment API - Zoom 22 for max precision
        endpoint = "/traffic/services/4/flowSegmentData/absolute/22/json"
        flow = client.get(endpoint, params={"point": f"{lat},{lon}"})
        
        data = flow.get("flowSegmentData", {})
        if not data or data.get("currentSpeed") is None:
            return code, None
            
        record = {
            "source": "tomtom",
            "traffic_source": "api",
            "ingest_time": datetime.now(timezone.utc),
            "ingest_batch_id": batch_id,
            "ward_code": str(code),
            "ward_name": point_data.get('ward', ''),
            "province_name": point_data.get('province', ''),
            "latitude": lat,
            "longitude": lon,
            "nearest_highway_type": point_data.get('nearest_highway_type', 'unknown'),
            "distance_to_road_km": point_data.get('distance_to_road_km', 0),
            "timestamp_utc": datetime.now(timezone.utc),
            "current_speed": float(data.get("currentSpeed")),
            "free_flow_speed": float(data.get("freeFlowSpeed")),
            "current_travel_time": int(data.get("currentTravelTime", 0)),
            "free_flow_travel_time": int(data.get("freeFlowTravelTime", 0)),
            "confidence": float(data.get("confidence", 0)),
            "road_closure": bool(data.get("roadClosure", False)),
            "raw_payload": str(data)
        }
        return code, record
        
    except Exception as e:
        logger.warning(f"Failed to fetch traffic for {code} ({lat},{lon}): {e}")
        return code, None

def interpolate_tier_2(all_wards, tier_1_results, batch_id):
    """
    Interpolate traffic for remaining wards using IDW + OSM Proxy.
    """
    if not tier_1_results:
        logger.error("No Tier 1 data available for interpolation.")
        return []

    # Prepare known points for KDTree
    known_coords = [[r['latitude'], r['longitude']] for r in tier_1_results]
    # We use congestion_ratio (0-1) as the interpolation target
    # Ratio = 1 - (Speed / FreeFlow)
    known_ratios = [1.0 - (r['current_speed'] / max(r['free_flow_speed'], 1.0)) for r in tier_1_results]
    known_speeds = [r['current_speed'] for r in tier_1_results]
    known_ff_speeds = [r['free_flow_speed'] for r in tier_1_results]
    
    tree = cKDTree(known_coords)
    
    tier_1_codes = set([r['ward_code'] for r in tier_1_results])
    tier_2_records = []
    
    for _, ward in all_wards.iterrows():
        code = str(ward['code'])
        if code in tier_1_codes:
            continue
            
        # 1. IDW Interpolation
        # Query nearest 10 neighbors
        dists, indices = tree.query([ward['lat'], ward['lon']], k=min(10, len(known_coords)))
        
        # Avoid division by zero
        dists = np.clip(dists, 1e-6, None)
        weights = 1.0 / (dists ** 2)
        total_weight = np.sum(weights)
        
        interp_ratio = np.sum(np.array([known_ratios[i] for i in indices]) * weights) / total_weight
        interp_ff = np.sum(np.array([known_ff_speeds[i] for i in indices]) * weights) / total_weight
        
        # 2. OSM Proxy
        osm_proxy = get_osm_proxy(ward.get('nearest_highway_type', 'unknown'), ward.get('distance_to_road_km', 0.5))
        
        # 3. Blending
        # 65% Interpolation + 35% OSM Context
        final_ratio = (interp_ratio * 0.65) + (osm_proxy * 0.35)
        # Cap at [0, 1]
        final_ratio = max(0, min(1, final_ratio))
        
        # Derive speed back
        final_speed = interp_ff * (1.0 - final_ratio)
        
        tier_2_records.append({
            "source": "tomtom",
            "traffic_source": "interpolated",
            "ingest_time": datetime.now(timezone.utc),
            "ingest_batch_id": batch_id,
            "ward_code": code,
            "ward_name": ward.get('ward', ''),
            "province_name": ward.get('province', ''),
            "latitude": ward['lat'],
            "longitude": ward['lon'],
            "nearest_highway_type": ward.get('nearest_highway_type', 'unknown'),
            "distance_to_road_km": ward.get('distance_to_road_km', 0),
            "timestamp_utc": datetime.now(timezone.utc),
            "current_speed": float(final_speed),
            "free_flow_speed": float(interp_ff),
            "current_travel_time": 0,
            "free_flow_travel_time": 0,
            "confidence": 0.5, # Mid confidence for interpolated
            "road_closure": False,
            "raw_payload": f"Interpolated from {len(indices)} neighbors + OSM Proxy"
        })
        
    return tier_2_records

def main():
    parser = argparse.ArgumentParser(description="TomTom High-Resolution Ingestion")
    parser.add_argument("--limit-tier1", type=int, default=600)
    parser.add_argument("--workers", type=int, default=None)
    parser.add_argument("--log-level", default="INFO")
    args = parser.parse_args()

    logging.basicConfig(level=args.log_level, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    
    # Load env
    load_dotenv(os.path.join(PROJECT_ROOT, '.env'))

    # Setup Tokens - Load from comma-separated string (GHA style) or individual keys
    tokens = []
    keys_str = os.environ.get("TOMTOM_API_KEYS")
    if keys_str:
        tokens = [t.strip() for t in keys_str.split(",") if t.strip()]
    
    # Fallback/Backward Compatibility for individual keys
    if not tokens:
        for i in ["", "_2", "_3", "_4"]:
            key = f"TOMTOM_API_KEY{i}"
            val = os.environ.get(key)
            if val: tokens.append(val.strip())
    
    if not tokens:
        logger.error("No TomTom tokens found in .env (expected TOMTOM_API_KEYS or TOMTOM_API_KEY)")
        sys.exit(1)
        
    token_manager = TokenManager(tokens, requests_per_minute=2500/(24*60)*60) # Approx rate limiter
    client = APIClient(
        base_url="https://api.tomtom.com",
        token_manager=token_manager,
        auth_header_name="key" # TomTom uses 'key' as param
    )
    
    writer = get_data_writer()
    batch_id = f"tomtom_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}"
    
    # 1. Load Wards and Select Tier 1
    all_wards = load_enriched_wards()
    tier_1 = select_tier_1(all_wards, limit=args.limit_tier1)
    
    logger.info(f"Starting Tier 1 ingestion for {len(tier_1)} points.")
    
    # 2. Phase 1: API Ingestion
    tier_1_results = []
    num_workers = args.workers or (len(tokens) * 10)
    
    with ThreadPoolExecutor(max_workers=num_workers) as executor:
        futures = {executor.submit(fetch_traffic_for_point, row, client, batch_id): row['code'] for _, row in tier_1.iterrows()}
        for future in as_completed(futures):
            code, record = future.result()
            if record:
                tier_1_results.append(record)
    
    logger.info(f"Tier 1 complete: {len(tier_1_results)} successful fetches.")
    
    # 3. Phase 2: Interpolation
    logger.info("Starting Phase 2: Spatial Interpolation for Tier 2.")
    tier_2_results = interpolate_tier_2(all_wards, tier_1_results, batch_id)
    
    # 4. Final Write
    total_records = tier_1_results + tier_2_results
    if total_records:
        writer.write_batch("raw_tomtom_traffic", total_records, source="tomtom")
        logger.info(f"Wrote {len(total_records)} traffic records to ClickHouse.")
        update_control(source="tomtom", records_ingested=len(total_records), success=True)
    else:
        logger.error("No traffic records gathered.")
        update_control(source="tomtom", records_ingested=0, success=False, error_message="No records")

if __name__ == "__main__":
    main()
