{{ config(
    materialized='table',
    engine='MergeTree()',
    order_by='(province, datetime_hour)',
    partition_by='toYYYYMM(datetime_hour)',
    tags=['pipeline_v2']
) }}

select
    datetime_hour,
    date,
    province,
    region_3,
    region_8,
    avg_aqi_us,
    avg_aqi_vn,
    pm25_avg,
    pm10_avg,
    co_avg,
    no2_avg,
    so2_avg,
    o3_avg,
    pm25_aqi,
    pm10_aqi,
    co_aqi,
    no2_aqi,
    so2_aqi,
    o3_aqi,
    total_ward_count,
    total_ward_count as aqiin_ward_count,
    toUInt64(0) as openweather_ward_count,
    observation_count as aqiin_observation_count,
    toUInt64(0) as openweather_observation_count,
    source_mix,
    confidence_score,
    confidence_level,
    last_ingested_at,
    raw_loaded_at,
    raw_sync_run_id,
    raw_sync_started_at,
    main_pollutant
from {{ ref('int_observed__province_hourly') }}

union all

select
    datetime_hour,
    date,
    province,
    region_3,
    region_8,
    avg_aqi_us,
    avg_aqi_vn,
    pm25_avg,
    pm10_avg,
    co_avg,
    no2_avg,
    so2_avg,
    o3_avg,
    pm25_aqi,
    pm10_aqi,
    co_aqi,
    no2_aqi,
    so2_aqi,
    o3_aqi,
    total_ward_count,
    toUInt64(0) as aqiin_ward_count,
    total_ward_count as openweather_ward_count,
    toUInt64(0) as aqiin_observation_count,
    observation_count as openweather_observation_count,
    source_mix,
    confidence_score,
    confidence_level,
    last_ingested_at,
    raw_loaded_at,
    raw_sync_run_id,
    raw_sync_started_at,
    main_pollutant
from {{ ref('int_ow__province_hourly') }}
