{{ config(
    materialized='view',
    tags=['pipeline_v2']
) }}

select
    datetime_hour,
    date,
    province,
    ward_code,
    region_3,
    region_8,
    'aqiin' as source,
    1.0 as source_weight,
    avg_aqi_us as final_aqi_us,
    avg_aqi_vn as final_aqi_vn,
    pm25_avg as pm25_value,
    pm10_avg as pm10_value,
    co_avg as co_value,
    no2_avg as no2_value,
    so2_avg as so2_value,
    o3_avg as o3_value,
    pm25_aqi,
    pm10_aqi,
    co_aqi,
    no2_aqi,
    so2_aqi,
    o3_aqi,
    main_pollutant as dominant_pollutant_us,
    main_pollutant as dominant_pollutant_vn,
    last_ingested_at as ingest_time,
    raw_loaded_at,
    raw_sync_run_id,
    raw_sync_started_at
from {{ ref('int_aqiin__ward_hourly') }}

union all

select
    datetime_hour,
    date,
    province,
    ward_code,
    region_3,
    region_8,
    'waqi' as source,
    1.0 as source_weight,
    avg_aqi_us as final_aqi_us,
    avg_aqi_vn as final_aqi_vn,
    pm25_avg as pm25_value,
    pm10_avg as pm10_value,
    co_avg as co_value,
    no2_avg as no2_value,
    so2_avg as so2_value,
    o3_avg as o3_value,
    pm25_aqi,
    pm10_aqi,
    co_aqi,
    no2_aqi,
    so2_aqi,
    o3_aqi,
    main_pollutant as dominant_pollutant_us,
    main_pollutant as dominant_pollutant_vn,
    last_ingested_at as ingest_time,
    raw_loaded_at,
    raw_sync_run_id,
    raw_sync_started_at
from {{ ref('int_waqi__ward_hourly') }}

union all

select
    datetime_hour,
    date,
    province,
    ward_code,
    region_3,
    region_8,
    'openweather' as source,
    0.5 as source_weight,
    avg_aqi_us as final_aqi_us,
    avg_aqi_vn as final_aqi_vn,
    pm25_avg as pm25_value,
    pm10_avg as pm10_value,
    co_avg as co_value,
    no2_avg as no2_value,
    so2_avg as so2_value,
    o3_avg as o3_value,
    pm25_aqi,
    pm10_aqi,
    co_aqi,
    no2_aqi,
    so2_aqi,
    o3_aqi,
    main_pollutant as dominant_pollutant_us,
    main_pollutant as dominant_pollutant_vn,
    last_ingested_at as ingest_time,
    raw_loaded_at,
    raw_sync_run_id,
    raw_sync_started_at
from {{ ref('int_ow__ward_hourly') }}
