from __future__ import annotations

import pytest

from python_jobs.text_to_sql.vanna_runtime import (
    RuntimeGenerationError,
    RuntimeNotConfiguredError,
    VannaRuntime,
)


class FakeVanna:
    def __init__(self):
        self.training_calls = []
        self.questions = []

    def train(self, **kwargs):
        self.training_calls.append(kwargs)
        return "trained"

    def generate_sql(self, *, question):
        self.questions.append(question)
        return "SELECT province, current_aqi_vn FROM dm_aqi_current_status LIMIT 100"


@pytest.mark.unit
def test_runtime_requires_groq_key_for_vanna(monkeypatch, semantic_dir):
    monkeypatch.delenv("GROQ_API_KEY", raising=False)

    runtime = VannaRuntime(str(semantic_dir))

    with pytest.raises(RuntimeNotConfiguredError):
        runtime.generate_sql(
            question="Which provinces had the worst AQI?",
            lang="en",
            standard="TCVN",
            session_id="session-1",
        )


@pytest.mark.unit
def test_runtime_uses_vanna_with_groq_backing(monkeypatch, semantic_dir):
    fake_vanna = FakeVanna()
    monkeypatch.setenv("GROQ_API_KEY", "test-groq-key")
    monkeypatch.setenv("GROQ_MODEL", "qwen/qwen3-32b")
    monkeypatch.setattr(
        VannaRuntime,
        "_create_vanna_client",
        lambda self: fake_vanna,
    )

    runtime = VannaRuntime(str(semantic_dir))
    result = runtime.generate_sql(
        question="Tinh nao co AQI cao nhat trong 24 gio qua?",
        lang="vi",
        standard="TCVN",
        session_id="session-2",
    )

    assert fake_vanna.questions == ["Tinh nao co AQI cao nhat trong 24 gio qua?"]
    assert any("ddl" in call for call in fake_vanna.training_calls)
    assert any("documentation" in call for call in fake_vanna.training_calls)
    assert result.sql.startswith("SELECT province")
    assert result.explanation == "Generated by Vanna OSS using the approved mart-only catalog."


@pytest.mark.unit
def test_runtime_extracts_sql_from_reasoning_response(monkeypatch, semantic_dir):
    class ChattyVanna(FakeVanna):
        def generate_sql(self, *, question):
            self.questions.append(question)
            return """
            with the available context, I should use the hourly table.

            SELECT province, MAX(avg_aqi_vn) AS max_aqi
            FROM fct_air_quality_ward_level_hourly
            WHERE datetime_hour >= now() - INTERVAL 24 HOUR
            GROUP BY province
            ORDER BY max_aqi DESC
            LIMIT 1;
            """

    fake_vanna = ChattyVanna()
    monkeypatch.setenv("GROQ_API_KEY", "test-groq-key")
    monkeypatch.setattr(
        VannaRuntime,
        "_create_vanna_client",
        lambda self: fake_vanna,
    )

    runtime = VannaRuntime(str(semantic_dir))
    result = runtime.generate_sql(
        question="Tinh nao co AQI cao nhat trong 24 gio qua?",
        lang="vi",
        standard="TCVN",
        session_id="session-2",
    )

    assert result.sql.startswith("SELECT province")
    assert "with the available context" not in result.sql
    assert "LIMIT 1" in result.sql


@pytest.mark.unit
def test_runtime_extracts_sql_from_markdown_fence(monkeypatch, semantic_dir):
    class FencedVanna(FakeVanna):
        def generate_sql(self, *, question):
            self.questions.append(question)
            return """
            <think>I should not leak this reasoning.</think>

            ```sql
            SELECT province, current_aqi_vn
            FROM dm_aqi_current_status
            LIMIT 10;
            ```
            """

    fake_vanna = FencedVanna()
    monkeypatch.setenv("GROQ_API_KEY", "test-groq-key")
    monkeypatch.setattr(
        VannaRuntime,
        "_create_vanna_client",
        lambda self: fake_vanna,
    )

    runtime = VannaRuntime(str(semantic_dir))
    result = runtime.generate_sql(
        question="AQI cao nhat?",
        lang="vi",
        standard="TCVN",
        session_id="session-4",
    )

    assert result.sql.startswith("SELECT province")
    assert "<think>" not in result.sql


@pytest.mark.unit
def test_runtime_wraps_vanna_generation_errors(monkeypatch, semantic_dir):
    class BrokenVanna:
        def train(self, **kwargs):
            return "trained"

        def generate_sql(self, *, question):
            raise RuntimeError("boom")

    monkeypatch.setenv("GROQ_API_KEY", "test-groq-key")
    monkeypatch.setattr(
        VannaRuntime,
        "_create_vanna_client",
        lambda self: BrokenVanna(),
    )

    runtime = VannaRuntime(str(semantic_dir))

    with pytest.raises(RuntimeGenerationError, match="Vanna SQL generation failed"):
        runtime.generate_sql(
            question="AQI cao nhat?",
            lang="vi",
            standard="TCVN",
            session_id="session-3",
        )
