"""
Bulk catalog curation using OM REST API.
No openmetadata-ingestion library needed — uses simple requests calls.

Usage:
    OM_URL=http://openmetadata:8585/api \
    OM_USER=admin@open-metadata.org \
    OM_PASS=admin \
    python python_jobs/jobs/openmetadata/curation_bulk.py

Environment variables:
    OM_URL: OpenMetadata API base URL
    OM_USER: OM admin username
    OM_PASS: OM admin password
"""

import os
import sys
import requests

OM_URL = os.environ.get('OM_URL', 'http://openmetadata:8585/api')
OM_USER = os.environ.get('OM_USER', 'admin@open-metadata.org')
OM_PASS = os.environ.get('OM_PASS', 'admin')


def om_login() -> str:
    """Login to OM and return JWT token."""
    r = requests.post(
        f"{OM_URL}/v1/users/login",
        json={"username": OM_USER, "password": OM_PASS},
        headers={"Content-Type": "application/json"},
        timeout=30,
    )
    r.raise_for_status()
    return r.json()["token"]


def patch_table(fqn: str,
                description: str = None,
                owner_name: str = None,
                tags: list = None,
                tier: str = None) -> None:
    """Apply curation to a table entity via JSON Patch (RFC 6902)."""
    token = om_login()
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {token}",
    }

    patch_ops = []

    if description:
        patch_ops.append({
            "op": "replace",
            "path": "/description",
            "value": description,
        })

    if owner_name:
        user_resp = requests.get(
            f"{OM_URL}/v1/users/name/{owner_name}",
            headers=headers,
            timeout=15,
        )
        if user_resp.ok:
            user_id = user_resp.json()["id"]
            patch_ops.append({
                "op": "replace",
                "path": "/owner",
                "value": {"id": user_id, "type": "user"},
            })

    if tags:
        patch_ops.append({
            "op": "replace",
            "path": "/tags",
            "value": [
                {"tagFQN": f"Data.{t}", "labelType": "Manual", "state": "Confirmed"}
                for t in tags
            ],
        })

    if tier:
        patch_ops.append({
            "op": "replace",
            "path": "/tier",
            "value": {"tagFQN": f"Tier.{tier}"},
        })

    if not patch_ops:
        return

    fqn_url = fqn.replace('.', '/')
    r = requests.patch(
        f"{OM_URL}/v1/tables/name/{fqn_url}",
        headers=headers,
        json=patch_ops,
        timeout=30,
    )
    if r.status_code == 404:
        print(f"⚠️  Table not found: {fqn} (skipping)")
        return
    r.raise_for_status()
    print(f"✅ Curated: {fqn}")


# ─── Curation definitions ────────────────────────────────────────────────────

MART_CURATION = [
    {
        "fqn": "air_quality.air_quality.fct_hourly_aqi",
        "description": (
            "Hourly AQI measurements per station and pollutant. Primary fact table for "
            "air quality analytics. Values normalized to US EPA AQI scale (0-500). "
            "Populated by dbt intermediate/int_unified__measurements. "
            "Serves Streamlit dashboard (Overview, Pollutants pages)."
        ),
        "owner": "admin",
        "tags": ["AirQuality", "Vietnam", "NoPII"],
        "tier": "Tier1",
    },
    {
        "fqn": "air_quality.air_quality.fct_daily_aqi_summary",
        "description": (
            "Daily AQI summary per station. Aggregates hourly measurements into daily "
            "min/max/avg/median AQI. Uses US EPA category breakpoints."
        ),
        "owner": "admin",
        "tags": ["AirQuality", "Vietnam", "NoPII"],
        "tier": "Tier1",
    },
    {
        "fqn": "air_quality.air_quality.fact_aqi_alerts",
        "description": (
            "Alert events when AQI exceeds WHO/US EPA exposure thresholds. "
            "Generated by dbt rules in intermediate/int_aqi_calculations. "
            "Serves as source for Streamlit alert notifications and Grafana alerts."
        ),
        "owner": "admin",
        "tags": ["AirQuality", "Alerts", "Vietnam", "NoPII"],
        "tier": "Tier1",
    },
    {
        "fqn": "air_quality.air_quality.dim_locations",
        "description": (
            "Dimension table for monitoring station locations across 63 provinces "
            "of Vietnam. Includes GPS coordinates (lat 8-24, lon 102-110), elevation, "
            "station type, and source attribution. Sourced from AQICN, OpenWeather, "
            "and Sensors.Community."
        ),
        "owner": "admin",
        "tags": ["AirQuality", "Vietnam", "NoPII"],
        "tier": "Tier2",
    },
    {
        "fqn": "air_quality.air_quality.dim_time",
        "description": (
            "Time dimension table. Pre-generated hourly buckets (2020-2030) for "
            "efficient time-series joins in analytical queries."
        ),
        "owner": "admin",
        "tags": ["AirQuality"],
        "tier": "Tier2",
    },
    {
        "fqn": "air_quality.air_quality.dim_pollutants",
        "description": (
            "Pollutant dimension. Defines PM2.5, PM10, O₃, NO₂, SO₂, CO with "
            "AQI breakpoints per pollutant per averaging period (1-hour, 8-hour, 24-hour)."
        ),
        "owner": "admin",
        "tags": ["AirQuality"],
        "tier": "Tier2",
    },
    {
        "fqn": "air_quality.air_quality.mart_air_quality__dashboard",
        "description": (
            "Pre-aggregated dashboard-ready dataset. Combines hourly AQI, dominant "
            "pollutant, forecast vs actual, and trend indicators. Primary source for "
            "Streamlit dashboard."
        ),
        "owner": "admin",
        "tags": ["AirQuality", "Dashboard", "Vietnam", "NoPII"],
        "tier": "Tier1",
    },
    {
        "fqn": "air_quality.air_quality.mart_air_quality__hourly",
        "description": "Hourly aggregated metrics per station per hour. Includes AQI, "
                        "pollutant breakdown, and data quality indicators.",
        "owner": "admin",
        "tags": ["AirQuality", "Vietnam", "NoPII"],
        "tier": "Tier2",
    },
    {
        "fqn": "air_quality.air_quality.mart_air_quality__daily_summary",
        "description": "Daily summary metrics per station. Includes min/max/avg AQI, "
                       "dominant pollutant, and sensor quality tier.",
        "owner": "admin",
        "tags": ["AirQuality", "Vietnam", "NoPII"],
        "tier": "Tier2",
    },
    {
        "fqn": "air_quality.air_quality.mart_air_quality__alerts",
        "description": "Alert events table for Streamlit dashboard. Derives from "
                       "fact_aqi_alerts with deduplication logic.",
        "owner": "admin",
        "tags": ["AirQuality", "Alerts", "Vietnam", "NoPII"],
        "tier": "Tier1",
    },
    {
        "fqn": "air_quality.air_quality.mart_air_quality__stations",
        "description": "Station metadata denormalized for dashboard display. "
                       "Joins AQICN stations, Sensors.Community sensors, and OpenWeather city metadata.",
        "owner": "admin",
        "tags": ["AirQuality", "Vietnam", "NoPII"],
        "tier": "Tier2",
    },
]

RAW_CURATION = [
    {
        "fqn": "air_quality.air_quality.raw_aqicn_measurements",
        "description": (
            "Raw AQICN/WAQI (api.waqi.info) measurement data ingested via Python jobs. "
            "Append-only MergeTree. Retains 100% original API payload in raw_payload column."
        ),
        "owner": "admin",
        "tags": ["Raw", "AQICN", "NoPII"],
        "tier": "Tier3",
    },
    {
        "fqn": "air_quality.air_quality.raw_aqicn_forecast",
        "description": (
            "Raw AQICN forecast data (3-day forecast per pollutant per station). "
            "ReplacingMergeTree, deduplicated on station_id + measurement_time_v + day."
        ),
        "owner": "admin",
        "tags": ["Raw", "AQICN", "NoPII"],
        "tier": "Tier3",
    },
    {
        "fqn": "air_quality.air_quality.raw_aqicn_stations",
        "description": (
            "Raw AQICN station metadata (name, geo, AQI, attribution). "
            "ReplacingMergeTree, deduplicated on station_id."
        ),
        "owner": "admin",
        "tags": ["Raw", "AQICN", "NoPII"],
        "tier": "Tier3",
    },
    {
        "fqn": "air_quality.air_quality.raw_sensorscm_measurements",
        "description": (
            "Raw Sensors.Community (sensor.community) sensor measurements. "
            "Deduplicated on sensor_id + timestamp. Includes PM2.5, PM10, "
            "temperature, humidity from SDS011/PMS5003 sensors."
        ),
        "owner": "admin",
        "tags": ["Raw", "SensorsCommunity", "NoPII"],
        "tier": "Tier3",
    },
    {
        "fqn": "air_quality.air_quality.raw_sensorscm_sensors",
        "description": (
            "Raw Sensors.Community sensor/station metadata. "
            "Deduplicated on sensor_id. Includes GPS, sensor_type, is_indoor."
        ),
        "owner": "admin",
        "tags": ["Raw", "SensorsCommunity", "NoPII"],
        "tier": "Tier3",
    },
    {
        "fqn": "air_quality.air_quality.raw_openweather_measurements",
        "description": (
            "Raw OpenWeather Air Pollution API measurements for 62 Vietnam provinces. "
            "Append-only MergeTree. Parameters: pm25, pm10, o3, no2, so2, co, nh3, no."
        ),
        "owner": "admin",
        "tags": ["Raw", "OpenWeather", "NoPII"],
        "tier": "Tier3",
    },
    {
        "fqn": "air_quality.air_quality.raw_openweather_forecast",
        "description": (
            "Raw OpenWeather Air Pollution 4-day forecast. Separated from measurements "
            "(future timestamps). ReplacingMergeTree."
        ),
        "owner": "admin",
        "tags": ["Raw", "OpenWeather", "NoPII"],
        "tier": "Tier3",
    },
    {
        "fqn": "air_quality.air_quality.ingestion_control",
        "description": (
            "Ingestion run metadata tracking. Logs source, last_run, records_ingested, "
            "lag_seconds, error_message per source. Consumed by Grafana freshness dashboards."
        ),
        "owner": "admin",
        "tags": ["Infrastructure", "NoPII"],
        "tier": "Tier3",
    },
]


def apply_all_curation():
    """Apply curation to all mart and raw tables."""
    print("Starting catalog curation...")
    all_tables = MART_CURATION + RAW_CURATION
    for i, table in enumerate(all_tables, 1):
        print(f"[{i}/{len(all_tables)}] Curating: {table['fqn']}")
        try:
            patch_table(
                fqn=table["fqn"],
                description=table.get("description"),
                owner_name=table.get("owner"),
                tags=table.get("tags"),
                tier=table.get("tier"),
            )
        except Exception as e:
            print(f"⚠️  Failed: {table['fqn']} — {e}")
    print(f"\n✅ Curation complete. Processed {len(all_tables)} tables.")


if __name__ == "__main__":
    apply_all_curation()
