"""
Setup OM glossary and terms for Air Quality domain.
Idempotent — safe to run repeatedly.

Usage:
    OM_URL=http://openmetadata:8585/api \
    OM_USER=admin@open-metadata.org \
    OM_PASS=admin \
    python python_jobs/jobs/openmetadata/setup_glossary.py
"""

import os
import requests

OM_URL = os.environ.get('OM_URL', 'http://openmetadata:8585/api')
OM_USER = os.environ.get('OM_USER', 'admin@open-metadata.org')
OM_PASS = os.environ.get('OM_PASS', 'admin')


def om_login() -> str:
    r = requests.post(
        f"{OM_URL}/v1/users/login",
        json={"username": OM_USER, "password": OM_PASS},
        headers={"Content-Type": "application/json"},
        timeout=30,
    )
    r.raise_for_status()
    return r.json()["token"]


GLOSSARY_NAME = "AirQuality"
GLOSSARY_DISPLAY_NAME = "Air Quality Glossary"

GLOSSARY_DEFINITIONS = [
    {
        "name": "AQI",
        "displayName": "Air Quality Index",
        "description": (
            "Composite air quality index on a 0–500 scale. Higher values indicate "
            "worse air quality. Categories: Good (0–50), Moderate (51–100), "
            "Unhealthy for Sensitive Groups (101–150), Unhealthy (151–200), "
            "Very Unhealthy (201–300), Hazardous (301–500). "
            "Based on US EPA standard. Used in fct_hourly_aqi, mart_air_quality__dashboard."
        ),
    },
    {
        "name": "PM25",
        "displayName": "PM2.5 — Fine Particulate Matter",
        "description": (
            "Airborne particles ≤ 2.5 micrometers diameter. Primary health risk "
            "in Vietnamese urban areas. WHO guideline: < 5 µg/m³ annual mean, "
            "< 15 µg/m³ 24-hour mean. Primary pollutant in Hanoi and HCMC. "
            "Used in stg_aqicn__measurements, stg_openweather__measurements, "
            "stg_sensorscm__measurements."
        ),
    },
    {
        "name": "PM10",
        "displayName": "PM10 — Coarse Particulate Matter",
        "description": (
            "Airborne particles ≤ 10 micrometers diameter. Generated by construction, "
            "agriculture, dust. WHO guideline: < 15 µg/m³ annual mean, "
            "< 45 µg/m³ 24-hour mean. Common in Vietnamese industrial provinces."
        ),
    },
    {
        "name": "Ozone",
        "displayName": "O₃ — Ground-Level Ozone",
        "description": (
            "Secondary pollutant formed by NOₓ + VOCs + sunlight via photochemical reactions. "
            "Peak levels in afternoon (12:00–18:00). WHO 8-hour guideline: < 100 µg/m³. "
            "Monitored via OpenWeather o3 parameter."
        ),
    },
    {
        "name": "NO2",
        "displayName": "NO₂ — Nitrogen Dioxide",
        "description": (
            "Traffic-related pollutant and respiratory irritant. Primary source: "
            "vehicle emissions, power plants. WHO 1-hour guideline: < 200 µg/m³. "
            "High in Hanoi and HCMC traffic corridors."
        ),
    },
    {
        "name": "SO2",
        "displayName": "SO₂ — Sulfur Dioxide",
        "description": (
            "Primarily from fossil fuel combustion (coal power plants, heavy industry). "
            "Affects respiratory system. WHO 10-minute guideline: < 500 µg/m³. "
            "Relevant in northern Vietnamese industrial zones."
        ),
    },
    {
        "name": "CO",
        "displayName": "CO — Carbon Monoxide",
        "description": (
            "Colorless, odorless gas from incomplete combustion (vehicles, cooking, heating). "
            "Affects blood oxygen carrying capacity at high concentrations. "
            "WHO 8-hour guideline: < 4 mg/m³ (approx. 3.5 ppm). "
            "Monitored via OpenWeather co parameter."
        ),
    },
]


def create_glossary() -> str:
    """Create or get existing AirQuality glossary. Returns glossary ID."""
    token = om_login()
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }

    # Try to get existing glossary first
    resp = requests.get(
        f"{OM_URL}/v1/glossaries/name/{GLOSSARY_NAME}",
        headers=headers,
        timeout=15,
    )
    if resp.ok:
        glossary_id = resp.json()["id"]
        print(f"ℹ️  Glossary '{GLOSSARY_NAME}' already exists, id={glossary_id}")
        return glossary_id

    # Create new glossary
    user_resp = requests.get(
        f"{OM_URL}/v1/users/name/admin",
        headers=headers,
        timeout=15,
    )
    owner_id = user_resp.json()["id"] if user_resp.ok else None

    create_payload = {
        "name": GLOSSARY_NAME,
        "displayName": GLOSSARY_DISPLAY_NAME,
        "description": (
            "Standard vocabulary for air quality metrics used in Vietnam Air Quality "
            "Data Platform. Covers AQI calculation, pollutants, data quality tiers, "
            "and alert thresholds."
        ),
        "status": "Approved",
    }
    if owner_id:
        create_payload["owner"] = {"id": owner_id, "type": "user"}

    resp = requests.post(
        f"{OM_URL}/v1/glossaries",
        headers=headers,
        json=create_payload,
        timeout=30,
    )
    if resp.status_code == 409:
        # Race condition: created by another process
        resp = requests.get(
            f"{OM_URL}/v1/glossaries/name/{GLOSSARY_NAME}",
            headers=headers,
            timeout=15,
        )
        resp.raise_for_status()
        glossary_id = resp.json()["id"]
    else:
        resp.raise_for_status()
        glossary_id = resp.json()["id"]

    print(f"✅ Created glossary '{GLOSSARY_NAME}', id={glossary_id}")
    return glossary_id


def create_terms(glossary_id: str):
    """Create glossary terms for all pollutants."""
    token = om_login()
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }

    for term in GLOSSARY_DEFINITIONS:
        term_payload = {
            "name": term["name"],
            "displayName": term["displayName"],
            "description": term["description"],
            "glossary": {"id": glossary_id, "type": "glossary"},
            "status": "Approved",
            "mutuallyExclusive": False,
        }
        term_resp = requests.post(
            f"{OM_URL}/v1/glossaryTerms",
            headers=headers,
            json=term_payload,
            timeout=30,
        )
        if term_resp.status_code == 409:
            print(f"  ⏭ Term '{term['name']}' already exists")
        elif term_resp.ok:
            print(f"  ✅ Created term: {term['name']}")
        else:
            print(f"  ❌ Failed to create {term['name']}: {term_resp.text}")


def setup_glossary():
    """Main entry point — create glossary and all terms."""
    print("Setting up AirQuality glossary...")
    glossary_id = create_glossary()
    print(f"\nCreating {len(GLOSSARY_DEFINITIONS)} glossary terms...")
    create_terms(glossary_id)
    print(f"\n✅ Glossary setup complete.")


if __name__ == "__main__":
    setup_glossary()
